export { default as Hero } from './Hero/Hero'
export { default as Categories } from './Categories/Categories'
export { default as Collections } from './Collections/Collections'
export { default as CreateYourNFT } from './CreateYourNFT/CreateYourNFT'
export { default as Market } from './Market/Market'